language: android
install:
  - curl -fsSL -o ndk.bin http://dl.google.com/android/ndk/android-ndk-r10c-linux-x86_64.bin
  - chmod +x ndk.bin
  - ./ndk.bin > /dev/null
  - export NDK_HOME=$(pwd)/$(ls -1|grep ndk|grep -v .bin)
  - export PATH=$PATH:$NDK_HOME
script:
  - chmod +x android-make.sh
  - ./android-make.sh 1.8.0
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: libuv_android.zip
  skip_cleanup: true
  on:
    tags: false
branches:
  only:
    - master  
    