language: android
language: android
android:
  components:
    - ndk
script:
  - chmod +x android-make.sh
  - ./android-make.sh 1.8.0
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: libuv_android.zip
  skip_cleanup: true
  on:
    tags: true
  
    