version: 0.{build}
environment:  
  vs_ver: vs2010
  tag_ver: 1.7.0 
cache: gyp
build_script:
- cmd: make.bat %tag_ver% %vs_ver%
artifacts:
- path: libuv.zip
skip_tags: true
deploy:
- provider: GitHub
  tag: libuv_$(tag_ver)_$(vs_ver)
  auth_token:
    secure: Ba9VKWqzpudkrypBUmM4ih6a+zC65UlmQD0DJkx1ffheHm3KozKCB8o92iSfzhm8
  artifact: libuv.zip
  force_update: true
