version: 0.{build}
environment:
  matrix:
  - vs_ver: vc100
    tag_ver: 1.7.0 
  - vs_ver: vc140
    tag_ver: 1.7.0 
  - vs_ver: vc140
    tag_ver: 1.8.0 
  - vs_ver: vc140
    tag_ver: 1.9.0
cache: gyp
build_script:
- cmd: win32-make.bat %tag_ver% %vs_ver%
artifacts:
- path: libuv_win32_$(vs_ver).zip
skip_tags: true
deploy:
- provider: GitHub
  tag: libuv_$(tag_ver)
  auth_token:
    secure: Ba9VKWqzpudkrypBUmM4ih6a+zC65UlmQD0DJkx1ffheHm3KozKCB8o92iSfzhm8
  artifact: libuv_win32_$(vs_ver).zip
  force_update: true
